import { model } from "@medusajs/framework/utils"

const OrderFinalization = model
  .define("gp_order_finalization", {
    id: model.id({ prefix: "gpfin" }).primaryKey(),
    order_id: model.text(),
    cart_id: model.text().nullable(),
    customer_id: model.text().nullable(),
    customer_email: model.text().nullable(),
    currency_code: model.text().default("usd"),
    status: model.text().default("needs_pack"),
    display_id: model.text().nullable(),
    estimated_item_total: model.number().nullable(),
    estimated_shipping_total: model.number().nullable(),
    estimated_tax_total: model.number().nullable(),
    estimated_discount_total: model.number().nullable(),
    estimated_order_total: model.number().nullable(),
    final_item_total: model.number().nullable(),
    final_shipping_total: model.number().nullable(),
    final_tax_total: model.number().nullable(),
    final_discount_total: model.number().nullable(),
    final_order_total: model.number().nullable(),
    delta_total: model.number().nullable(),
    started_at: model.dateTime().nullable(),
    started_by: model.text().nullable(),
    packed_at: model.dateTime().nullable(),
    packed_by: model.text().nullable(),
    reviewed_at: model.dateTime().nullable(),
    reviewed_by: model.text().nullable(),
    charge_attempted_at: model.dateTime().nullable(),
    charged_by: model.text().nullable(),
    charged_at: model.dateTime().nullable(),
    charge_attempt_id: model.text().nullable(),
    released_at: model.dateTime().nullable(),
    released_by: model.text().nullable(),
    blocked_reason: model.text().nullable(),
    customer_consent_required: model.boolean().default(false),
    customer_consent_status: model.text().default("not_required"),
    override_required: model.boolean().default(false),
    override_reason: model.text().nullable(),
    manager_approved_by: model.text().nullable(),
    manager_approved_at: model.dateTime().nullable(),
    stripe_payment_intent_id: model.text().nullable(),
    stripe_charge_id: model.text().nullable(),
    stripe_failure_code: model.text().nullable(),
    stripe_failure_message: model.text().nullable(),
    qbd_posting_required: model.boolean().default(false),
    qbd_posting_status: model.text().nullable(),
    qbd_posting_action: model.text().nullable(),
    qbd_posting_request_key: model.text().nullable(),
    final_charge_email_sent_at: model.dateTime().nullable(),
    note: model.text().nullable(),
    metadata: model.json().nullable(),
  })
  .indexes([
    {
      name: "IDX_gp_order_finalization_order",
      on: ["order_id"],
      where: "deleted_at IS NULL",
    },
    {
      name: "IDX_gp_order_finalization_status",
      on: ["status", "created_at"],
      where: "deleted_at IS NULL",
    },
    {
      name: "IDX_gp_order_finalization_customer",
      on: ["customer_id"],
      where: "deleted_at IS NULL",
    },
  ])

export default OrderFinalization
